# Generated by Django 6.1.1 on 2026-09-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("website", models.URLField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("career_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Geplant"),
                            ("APPLIED", "Beworben"),
                            ("INTERVIEW", "Interview"),
                            ("ACCEPTED", "Zusage"),
                            ("REJECTED", "Absage"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("application_date", models.DateField(blank=True, null=True)),
                ("job_url", models.URLField(blank=True)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("next_action", models.CharField(blank=True, max_length=255)),
                ("next_action_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="applications.company",
                    ),
                ),
            ],
        ),
    ]
